[build]
  publish = "." 
  functions = "netlify/functions"

# ✅ مهم جدًا: السماح بالوصول لملفات التحقق
[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

# 1. توجيه روابط العقارات
[[redirects]]
  from = "/property/:id"
  to = "/.netlify/functions/property?id=:id"
  status = 200
  force = true

# 2. fallback للموقع
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200